import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Theme } from "@/lib/theme";
import CssBaseline from "@mui/material/CssBaseline";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@chatbook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <CssBaseline/>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
